version: "3.4"

services:
  php:
    build: .
    volumes:
      # Comment out the next line in production
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    ports:
    - "80:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public

  db:
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: secret
    volumes:
    - ./docker/data/mysql:/var/lib/mysql:cached