<?php
/**
 * codekunst GmbH <www.codekunst.com>
 * @author e <hello@codekunst.com>
 */

namespace App\Tests\Service;

use App\Service\Calculator;
use PHPUnit\Framework\TestCase;

class CalculatorTest extends TestCase
{

    private Calculator $calculator;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->calculator = new Calculator();
    }


    public function numberProvider()
    {
        $data = [];

        for ($i = -50; $i < 50; $i++) {
            for ($j = -10; $j < 10; $j++) {
                $data [] = [$i, $j];
            }
        }

        return $data;

    }

    /**
     * @dataProvider numberProvider
     */
    public function testAdd($a, $b)
    {
        $this->assertEquals($a + $b, $this->calculator->add($a, $b));
    }

    /**
     * @dataProvider numberProvider
     */
    public function testDivide($a, $b)
    {
        $result = $b == 0 ? -1 : $a / $b;
        $this->assertEquals($result, $this->calculator->divide($a, $b));
    }


}
